# Generated by Django 4.1.2 on 2022-11-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paymenthistory", old_name="user_id", new_name="related_user",
        ),
        migrations.RenameField(
            model_name="subscription", old_name="user_id", new_name="related_user",
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="sub_type",
            field=models.CharField(
                choices=[("Monthly", "Monthly"), ("Yearly", "Yearly")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="sub_type",
            field=models.CharField(
                choices=[("Monthly", "Monthly"), ("Yearly", "Yearly")], max_length=10
            ),
        ),
    ]
