# Generated by Django 4.1.2 on 2022-11-17 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Subscriptions", "0002_rename_user_id_paymenthistory_related_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymenthistory",
            name="sub_type",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="is_subbed",
        ),
        migrations.AlterField(
            model_name="paymenthistory",
            name="payment_amount",
            field=models.FloatField(
                choices=[(14.99, "Monthly: $14.99"), (149.99, "Yearly: $149.99")]
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="related_user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="sub_type",
            field=models.FloatField(
                choices=[(14.99, "Monthly: $14.99"), (149.99, "Yearly: $149.99")]
            ),
        ),
    ]
